const ADDRESS_ITEM_TAG = 'div';
const ADDRESS_ITEM_CLASS = 'address-item';

const ADDRESS_ITEM_ID_ATTRIBUTE = 'data-address-id';

const DELETE_ADDRESS_BTN_TEXT = 'Delete';
const DELETE_ADDRESS_BTN_CLASSES = ['modal__btn', 'modal__btn_cancel'];

const CHECKBOX_WRAPPER_TAG = 'div';
const CHECKBOX_WRAPPER_CLASS = 'address-item__checkbox-wrapper';

const INPUTS_WRAPPER_TAG = 'div';
const INPUTS_WRAPPER_CLASS = 'address-item__inputs-wrapper';

const WRAPPER_TAG = 'div';
const WRAPPER_CLASS = 'address-item__wrapper';

const IS_SHIPPING_CHECKBOX_TEXT = 'Shipping';
const IS_DEFAULT_SHIPPING_CHECKBOX_TEXT = 'Default shipping';
const IS_BILLING_CHECKBOX_TEXT = 'Billing';
const IS_DEFAULT_BILLING_CHECKBOX_TEXT = 'Default billing';

export {
  ADDRESS_ITEM_TAG,
  ADDRESS_ITEM_CLASS,
  ADDRESS_ITEM_ID_ATTRIBUTE,
  DELETE_ADDRESS_BTN_TEXT,
  DELETE_ADDRESS_BTN_CLASSES,
  CHECKBOX_WRAPPER_TAG,
  CHECKBOX_WRAPPER_CLASS,
  INPUTS_WRAPPER_TAG,
  INPUTS_WRAPPER_CLASS,
  WRAPPER_TAG,
  WRAPPER_CLASS,
  IS_SHIPPING_CHECKBOX_TEXT,
  IS_DEFAULT_SHIPPING_CHECKBOX_TEXT,
  IS_BILLING_CHECKBOX_TEXT,
  IS_DEFAULT_BILLING_CHECKBOX_TEXT,
};
