export const country = {
  title: 'Select country',
  AM: 'Armenia',
  AZ: 'Azerbaijan',
  BY: 'Belarus',
  FI: 'Finland',
  FR: 'France',
  GE: 'Georgia',
  DE: 'Germany',
  JP: 'Japan',
  LV: 'Latvia',
  RU: 'Russia',
  ES: 'Spain',
  SE: 'Sweden',
  UA: 'Ukraine',
  GB: 'United Kingdom',
  US: 'United States',
  UZ: 'Uzbekistan',
};
